enum RememBarDiagnosticEvent {
    // Diagnostics/session lifecycle.
    static let diagnosticsPreviousSessionUnclean = "diagnostics.previous_session_unclean"
    static let diagnosticsSessionStarted = "diagnostics.session.started"
    static let diagnosticsSessionEnded = "diagnostics.session.ended"
    static let diagnosticsWriteFailed = "diagnostics.write_failed"
    static let diagnosticsCrashReportFound = "diagnostics.crash_report.found"
    static let diagnosticsCrashReportMissing = "diagnostics.crash_report.missing"

    // UI and user actions.
    static let uiMenuOpened = "ui.menu.opened"
    static let uiPanelRepositioned = "ui.panel.repositioned"
    static let searchSubmit = "search.submit"
    static let searchSubmitIgnored = "search.submit.ignored"
    static let searchClear = "search.clear"
    static let searchDebounceScheduled = "search.debounce.scheduled"
    static let searchDebounceFired = "search.debounce.fired"
    static let searchDebounceCancelled = "search.debounce.cancelled"
    static let searchStarted = "search.started"
    static let searchCancelledAfterProvider = "search.cancelled_after_provider"
    static let searchFinished = "search.finished"
    static let resultSelect = "result.select"
    static let resultOpenRequested = "result.open.requested"
    static let resultOpenWeb = "result.open.web"
    static let resultOpenFile = "result.open.file"
    static let resultOpenSystemSettings = "result.open.system_settings"
    static let resultOpenExternalApp = "result.open.external_app"
    static let resultOpenExternalAppRejected = "result.open.external_app.rejected"
    static let browserOpenRejected = "browser.open.rejected"
    static let browserOpenStarted = "browser.open.started"

    // Search provider boundaries.
    static let compositeSearchStarted = "composite.search.started"
    static let compositeProviderStarted = "composite.provider.started"
    static let compositeProviderFinished = "composite.provider.finished"
    static let compositeSearchFinished = "composite.search.finished"
    static let spotlightProviderEmptyPlan = "spotlight.provider.empty_plan"
    static let spotlightProviderStarted = "spotlight.provider.started"
    static let spotlightProviderFinished = "spotlight.provider.finished"
    static let spotlightProviderFailed = "spotlight.provider.failed"
    static let fileSearchAccessDenied = "file_search.access.denied"
    static let historyProviderStarted = "history.provider.started"
    static let historyProviderFinished = "history.provider.finished"
    static let historyReadStarted = "history.read.started"
    static let historyDiscoveryFinished = "history.discovery.finished"
    static let historySourceReadStarted = "history.source.read.started"
    static let historySourceReadFinished = "history.source.read.finished"
    static let historySourceReadFailed = "history.source.read.failed"
    static let onePasswordProviderFailed = "onepassword.provider.failed"

    // Term-families (alias) catalog — in-app edits + live reload.
    static let aliasCatalogUpdated = "alias.catalog.updated"
    static let aliasCatalogReloaded = "alias.catalog.reloaded"
    static let aliasCatalogSaveFailed = "alias.catalog.save_failed"

    // External process and thumbnail boundaries.
    static let mdfindSearchCancelRequested = "mdfind.search.cancel.requested"
    static let mdfindProcessCancelledBeforeLaunch = "mdfind.process.cancelled_before_launch"
    static let mdfindProcessLaunch = "mdfind.process.launch"
    static let mdfindProcessLaunchFailed = "mdfind.process.launch.failed"
    static let mdfindProcessLaunched = "mdfind.process.launched"
    static let mdfindProcessCancelRequestedAfterLaunch = "mdfind.process.cancel_requested_after_launch"
    static let mdfindProcessTimeout = "mdfind.process.timeout"
    static let mdfindProcessCancelled = "mdfind.process.cancelled"
    static let mdfindProcessFailed = "mdfind.process.failed"
    static let mdfindProcessFinished = "mdfind.process.finished"
    static let thumbnailQuickLookStarted = "thumbnail.quicklook.started"
    static let thumbnailQuickLookFinished = "thumbnail.quicklook.finished"
    static let thumbnailQuickLookFailed = "thumbnail.quicklook.failed"
    static let thumbnailQuickLookCancelled = "thumbnail.quicklook.cancelled"
    static let thumbnailRemoteStarted = "thumbnail.remote.started"
    static let thumbnailRemoteFinished = "thumbnail.remote.finished"
    static let thumbnailRemoteFailed = "thumbnail.remote.failed"
    static let thumbnailRemoteCancelled = "thumbnail.remote.cancelled"
}
